# Generated by Django 5.1.3 on 2024-12-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.cartitem'),
        ),
    ]
