# Generated by Django 5.1.3 on 2024-12-02 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_orderitem_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cart_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.cartitem'),
        ),
    ]
