# Generated by Django 5.1.3 on 2024-12-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_cart_processed_alter_orderitem_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
