# Generated by Django 5.1.3 on 2024-12-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_cart_processed_cartitem_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('In transit', 'In transit'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=10),
        ),
    ]
